server:
  port: 8080

stats-server:
  url: http://localhost:9090

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: postgres
    username: root
    url: jdbc:postgresql://ewm-db:5432/ewm_db

  config:
    activate:
      on-profile: ci,test,default

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        orm:
          jpa:
            JpaTransactionManager: DEBUG
            nodeValue: INFO
        transaction:
          interceptor: TRACE
          nodeValue: INFO
