DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS events_to_compilations CASCADE;


CREATE TABLE IF NOT EXISTS users
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    e_mail VARCHAR(255)                            NOT NULL,
    name   VARCHAR(512)                            NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (e_mail)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(64)                             NOT NULL,
    CONSTRAINT PK_CAT PRIMARY KEY (id),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);



CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title              VARCHAR                                 NOT NULL,
    annotation         VARCHAR                                 NOT NULL,
    description        VARCHAR,
    created_on         TIMESTAMP                               NOT NULL,
    published_on       TIMESTAMP,
    event_date         TIMESTAMP                               NOT NULL,
    paid               BOOLEAN                                 NOT NULL,
    request_moderation BOOLEAN                                 NOT NULL,
    participant_limit  INTEGER                                 NOT NULL,
    confirmed_requests INTEGER                                 NOT NULL,
    LAT                FLOAT                                   NOT NULL,
    LON                FLOAT                                   NOT NULL,
    state              VARCHAR                                 NOT NULL,
    category           BIGINT REFERENCES categories (id) ON DELETE CASCADE,
    initiator          BIGINT REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT PK_EVENT PRIMARY KEY (id)
);



CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title  VARCHAR                                 NOT NULL,
    pinned BOOLEAN                                 NOT NULL,
    CONSTRAINT PK_COMP PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_on TIMESTAMP                               NOT NULL,
    status     VARCHAR(64)                             NOT NULL,
    requester  BIGINT REFERENCES users (id) ON DELETE CASCADE,
    event      BIGINT REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT PK_REQ PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events_to_compilations
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id       BIGINT,
    compilation_id BIGINT,
    CONSTRAINT fk_events_to_compilations_event_id FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT fk_events_to_compilations_compilation_id FOREIGN KEY (compilation_id) REFERENCES compilations (id)
);