server:
  port: 9090

stats-server:
  url: http://localhost:9090


spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: root
    username: postgres
    url: jdbc:postgresql://stats-db:5432/stats_db

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        orm:
          jpa:
            JpaTransactionManager: DEBUG
            nodeValue: INFO
        transaction:
          interceptor: TRACE
          nodeValue: INFO

