version: '3.1'
services:
  stats-server:
    build: stats-service/stats-server
    image: ewm-stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stats-db
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=GSBoldyrev
      - POSTGRES_PASSWORD=GSBoldyrev

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=GSBoldyrev
      - POSTGRES_PASSWORD=GSBoldyrev

  ewm-service:
    build: ewm-service
    image: ewm-service
    container_name: explore-with-me-ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5433/ewm-db
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=root123
      - POSTGRES_PASSWORD=root123
      - STATS_SERVER_URL=http://server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5433"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=GSBoldyrev
      - POSTGRES_PASSWORD=GSBoldyrev


    